### ISSUE TITLE
No event choosen yet

### ISSUE THREAD

**Issue by manjulaongc** [keurfonluu/Pycker#4]
After opening pycker, selected directory having segy files
when try to import any segy file it is giving error "no event chosen yet"
Pl kindly help me.

**Comment by keurfonluu** [comment]
Hi,

Can you provide a screenshot of the whole window. Normally, you should double-click on a file in the list to open it.

**Comment by manjulaongc** [comment]
Hi
Thank you for quick response.
We could open the segy file and do picking on it but when trying to zoom and pick, picking is not working. 
Also the text file generated after picking contains only time values.
Can we have output text file with required header values like depth, coordinates and time
Looking forward for your help

**Comment by keurfonluu** [comment]
Truly sorry for the late reply.

What's the error when you try to pick?

This package was initially developed to mimic the picker program in Seismic Unix. You can get header information directly from your segy file with Obspy.

**Comment by manjulaongc** [comment]
Thank you for your response

Now only I have seen your msg as i am in my office trip.

It was our mistake that we were doing wrong while picking first breaks in
zoom option. Now picking is working fine.

Thank you once again

Manjula Singamsetty
